openapi: 3.0.2
info:
  title: RIoTPoT API
  version: "1.0"
  contact:
    email: ricardoyaben@gmail.com
    name: Ricardo Yaben
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/

servers:
  - url: api
    description: API path for riotpot
tags:
  - name: Proxies
  - name: Services

components:
  schemas:
    Px:
      $ref: Px.yaml
    Proxy:
      $ref: Proxy.yaml
    Service:
      $ref: Service.yaml
paths:
  # Proxies
  /proxies:
    $ref: proxies.yaml#/~1
  /proxies/{id}:
    $ref: proxies.yaml#/~1{id}
  /proxies/{id}/status:
    $ref: proxies.yaml#/~1{id}~1status

  # Services
  /services:
    $ref: services.yaml#/~1
  /services/{id}:
    $ref: services.yaml#/~1{id}
