---
# RiotPot configuration file.
# This file can be used as a template for further implementations and as a record of
# documentation for internal structure when in doubt on usage.
riotpot:
  # The name of the services is the name of the folder in which the plugin
  # is stored, inside the `pkg/` folder.
  # Example:
  #   * if the plugin is stored in: `pkg/telnetd`
  #   * then place: `- telnetd`

  # Contains a list of available services in the application.
  # This gives the user the ability to navigate or load
  # just the emulators that appear in this list, wether or not
  # the emulator plugin appears in the binary.
  #
  # Add here the emulator plugins you have included on the binary.
  emulators:
    - httpd
    - echod
    - sshd
    - telnetd
    - mqttd
    - coapd
    - modbusd

  # `start` contains a list of services desired to be run
  # on-start variable used in Riotpot core on runtime only!
  # For all the services leave it empty
  start: []
