openapi: "3.0.2"
info:
  title: RIoTPoT API
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      description: "Test endpoint"
      responses:
        "200":
          description: OK
