name: react

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - "gsoc_2022"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - run: cd ui
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm run build --if-present
        working-directory: ./ui
      - run: npx semantic-release
        working-directory: ./ui
